<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title><?php echo $this->translate("Unauthorized"); ?></title>
</head>
<body>
  <h1><?php echo $this->translate("Unauthorized"); ?></h1>
  <p><?php echo $this->translate("You have been banned from this site due to multiple invalid login attempts"); ?></p>
</body>
</html>
